use crate::cf_fcncode_values::*;

// Command code constants
pub const CF_NOOP_CC: u8 = CF_CCVAL_NOOP;
pub const CF_RESET_CC: u8 = CF_CCVAL_RESET_COUNTERS;
pub const CF_TX_FILE_CC: u8 = CF_CCVAL_TX_FILE;
pub const CF_PLAYBACK_DIR_CC: u8 = CF_CCVAL_PLAYBACK_DIR;
pub const CF_FREEZE_CC: u8 = CF_CCVAL_FREEZE;
pub const CF_THAW_CC: u8 = CF_CCVAL_THAW;
pub const CF_SUSPEND_CC: u8 = CF_CCVAL_SUSPEND;
pub const CF_RESUME_CC: u8 = CF_CCVAL_RESUME;
pub const CF_CANCEL_CC: u8 = CF_CCVAL_CANCEL;
pub const CF_ABANDON_CC: u8 = CF_CCVAL_ABANDON;
pub const CF_SET_PARAM_CC: u8 = CF_CCVAL_SET_PARAM;
pub const CF_GET_PARAM_CC: u8 = CF_CCVAL_GET_PARAM;
pub const CF_WRITE_QUEUE_CC: u8 = CF_CCVAL_WRITE_QUEUE;
pub const CF_ENABLE_DEQUEUE_CC: u8 = CF_CCVAL_ENABLE_DEQUEUE;
pub const CF_DISABLE_DEQUEUE_CC: u8 = CF_CCVAL_DISABLE_DEQUEUE;
pub const CF_ENABLE_DIR_POLLING_CC: u8 = CF_CCVAL_ENABLE_DIR_POLLING;
pub const CF_DISABLE_DIR_POLLING_CC: u8 = CF_CCVAL_DISABLE_DIR_POLLING;
pub const CF_PURGE_QUEUE_CC: u8 = CF_CCVAL_PURGE_QUEUE;
pub const CF_ENABLE_ENGINE_CC: u8 = CF_CCVAL_ENABLE_ENGINE;
pub const CF_DISABLE_ENGINE_CC: u8 = CF_CCVAL_DISABLE_ENGINE;

pub const CF_NUM_COMMANDS: u8 = 24;