use std::ffi::c_char;

// Application Pipe Depth
pub const CF_PIPE_DEPTH: i32 = CF_INTERNAL_CFGVAL_PIPE_DEPTH;
pub const DEFAULT_CF_PIPE_DEPTH: i32 = 32;

// Number of max commanded playbook files per chan
pub const CF_MAX_COMMANDED_PLAYBACK_FILES_PER_CHAN: i32 = CF_INTERNAL_CFGVAL_MAX_COMMANDED_PLAYBACK_FILES_PER_CHAN;
pub const DEFAULT_CF_MAX_COMMANDED_PLAYBACK_FILES_PER_CHAN: i32 = 10;

// Max number of simultaneous file receives
pub const CF_MAX_SIMULTANEOUS_RX: i32 = CF_INTERNAL_CFGVAL_MAX_SIMULTANEOUS_RX;
pub const DEFAULT_CF_MAX_SIMULTANEOUS_RX: i32 = 5;

// Max number of commanded playback directories per channel
pub const CF_MAX_COMMANDED_PLAYBACK_DIRECTORIES_PER_CHAN: i32 = CF_INTERNAL_CFGVAL_MAX_COMMANDED_PLAYBACK_DIRECTORIES_PER_CHAN;
pub const DEFAULT_CF_MAX_COMMANDED_PLAYBACK_DIRECTORIES_PER_CHAN: i32 = 2;

// Number of histories per channel
pub const CF_NUM_HISTORIES_PER_CHANNEL: i32 = CF_INTERNAL_CFGVAL_NUM_HISTORIES_PER_CHANNEL;
pub const DEFAULT_CF_NUM_HISTORIES_PER_CHANNEL: i32 = 256;

// Number of transactions per playback directory
pub const CF_NUM_TRANSACTIONS_PER_PLAYBACK: i32 = CF_INTERNAL_CFGVAL_NUM_TRANSACTIONS_PER_PLAYBACK;
pub const DEFAULT_CF_NUM_TRANSACTIONS_PER_PLAYBACK: i32 = 5;

// Name of the CF Configuration Table
pub const CF_CONFIG_TABLE_NAME: &str = CF_INTERNAL_CFGVAL_CONFIG_TABLE_NAME;
pub const DEFAULT_CF_CONFIG_TABLE_NAME: &str = "config_table";

// CF Configuration Table Filename
pub const CF_CONFIG_TABLE_FILENAME: &str = CF_INTERNAL_CFGVAL_CONFIG_TABLE_FILENAME;
pub const DEFAULT_CF_CONFIG_TABLE_FILENAME: &str = "/cf/cf_def_config.tbl";

// R2 CRC calc chunk size
pub const CF_R2_CRC_CHUNK_SIZE: i32 = CF_INTERNAL_CFGVAL_R2_CRC_CHUNK_SIZE;
pub const DEFAULT_CF_R2_CRC_CHUNK_SIZE: i32 = 1024;

// Number of milliseconds to wait for a SB message
pub const CF_RCVMSG_TIMEOUT: i32 = CF_INTERNAL_CFGVAL_RCVMSG_TIMEOUT;
pub const DEFAULT_CF_RCVMSG_TIMEOUT: i32 = 100;

// Limits the number of retries to obtain the CF throttle sem
pub const CF_STARTUP_SEM_MAX_RETRIES: i32 = CF_INTERNAL_CFGVAL_STARTUP_SEM_MAX_RETRIES;
pub const DEFAULT_CF_STARTUP_SEM_MAX_RETRIES: i32 = 25;

// Number of milliseconds to wait if CF throttle sem is not available
pub const CF_STARTUP_SEM_TASK_DELAY: i32 = CF_INTERNAL_CFGVAL_STARTUP_SEM_TASK_DELAY;
pub const DEFAULT_CF_STARTUP_SEM_TASK_DELAY: i32 = 100;

// Placeholder constants for CF_INTERNAL_CFGVAL macro expansion
// These would normally be defined in cf_internal_cfg_values.h
const CF_INTERNAL_CFGVAL_PIPE_DEPTH: i32 = DEFAULT_CF_PIPE_DEPTH;
const CF_INTERNAL_CFGVAL_MAX_COMMANDED_PLAYBACK_FILES_PER_CHAN: i32 = DEFAULT_CF_MAX_COMMANDED_PLAYBACK_FILES_PER_CHAN;
const CF_INTERNAL_CFGVAL_MAX_SIMULTANEOUS_RX: i32 = DEFAULT_CF_MAX_SIMULTANEOUS_RX;
const CF_INTERNAL_CFGVAL_MAX_COMMANDED_PLAYBACK_DIRECTORIES_PER_CHAN: i32 = DEFAULT_CF_MAX_COMMANDED_PLAYBACK_DIRECTORIES_PER_CHAN;
const CF_INTERNAL_CFGVAL_NUM_HISTORIES_PER_CHANNEL: i32 = DEFAULT_CF_NUM_HISTORIES_PER_CHANNEL;
const CF_INTERNAL_CFGVAL_NUM_TRANSACTIONS_PER_PLAYBACK: i32 = DEFAULT_CF_NUM_TRANSACTIONS_PER_PLAYBACK;
const CF_INTERNAL_CFGVAL_CONFIG_TABLE_NAME: &str = DEFAULT_CF_CONFIG_TABLE_NAME;
const CF_INTERNAL_CFGVAL_CONFIG_TABLE_FILENAME: &str = DEFAULT_CF_CONFIG_TABLE_FILENAME;
const CF_INTERNAL_CFGVAL_R2_CRC_CHUNK_SIZE: i32 = DEFAULT_CF_R2_CRC_CHUNK_SIZE;
const CF_INTERNAL_CFGVAL_RCVMSG_TIMEOUT: i32 = DEFAULT_CF_RCVMSG_TIMEOUT;
const CF_INTERNAL_CFGVAL_STARTUP_SEM_MAX_RETRIES: i32 = DEFAULT_CF_STARTUP_SEM_MAX_RETRIES;
const CF_INTERNAL_CFGVAL_STARTUP_SEM_TASK_DELAY: i32 = DEFAULT_CF_STARTUP_SEM_TASK_DELAY;