use std::os::raw::{c_char, c_int, c_uint};

// CF_INTERFACE_CFGVAL macro - assuming it returns the value or default
// This would need to be implemented based on the actual cf_interface_cfg_values.h
macro_rules! CF_INTERFACE_CFGVAL {
    (NUM_CHANNELS) => { DEFAULT_CF_NUM_CHANNELS };
    (NAK_MAX_SEGMENTS) => { DEFAULT_CF_NAK_MAX_SEGMENTS };
    (MAX_POLLING_DIR_PER_CHAN) => { DEFAULT_CF_MAX_POLLING_DIR_PER_CHAN };
    (MAX_PDU_SIZE) => { DEFAULT_CF_MAX_PDU_SIZE };
    (FILENAME_MAX_NAME) => { DEFAULT_CF_FILENAME_MAX_NAME };
    (FILENAME_MAX_LEN) => { DEFAULT_CF_FILENAME_MAX_LEN };
    (PDU_ENCAPSULATION_EXTRA_TRAILING_BYTES) => { DEFAULT_CF_PDU_ENCAPSULATION_EXTRA_TRAILING_BYTES };
}

// CFE_MISSION_MAX_FILE_LEN and CFE_MISSION_MAX_PATH_LEN would come from cfe_mission_cfg
// Assuming typical values for now
pub const CFE_MISSION_MAX_FILE_LEN: u32 = 64;
pub const CFE_MISSION_MAX_PATH_LEN: u32 = 256;

pub const DEFAULT_CF_NUM_CHANNELS: u32 = 2;
pub const DEFAULT_CF_NAK_MAX_SEGMENTS: u32 = 58;
pub const DEFAULT_CF_MAX_POLLING_DIR_PER_CHAN: u32 = 5;
pub const DEFAULT_CF_MAX_PDU_SIZE: u32 = 512;
pub const DEFAULT_CF_FILENAME_MAX_NAME: u32 = CFE_MISSION_MAX_FILE_LEN;
pub const DEFAULT_CF_FILENAME_MAX_LEN: u32 = CFE_MISSION_MAX_PATH_LEN;
pub const DEFAULT_CF_PDU_ENCAPSULATION_EXTRA_TRAILING_BYTES: u32 = 0;

pub const CF_NUM_CHANNELS: u32 = CF_INTERFACE_CFGVAL!(NUM_CHANNELS);
pub const CF_NAK_MAX_SEGMENTS: u32 = CF_INTERFACE_CFGVAL!(NAK_MAX_SEGMENTS);
pub const CF_MAX_POLLING_DIR_PER_CHAN: u32 = CF_INTERFACE_CFGVAL!(MAX_POLLING_DIR_PER_CHAN);
pub const CF_MAX_PDU_SIZE: u32 = CF_INTERFACE_CFGVAL!(MAX_PDU_SIZE);
pub const CF_FILENAME_MAX_NAME: u32 = CF_INTERFACE_CFGVAL!(FILENAME_MAX_NAME);
pub const CF_FILENAME_MAX_LEN: u32 = CF_INTERFACE_CFGVAL!(FILENAME_MAX_LEN);
pub const CF_PDU_ENCAPSULATION_EXTRA_TRAILING_BYTES: u32 = CF_INTERFACE_CFGVAL!(PDU_ENCAPSULATION_EXTRA_TRAILING_BYTES);