pub const CF_CHANNEL_NUM_RX_CHUNKS_PER_TRANSACTION: [u32; 2] = [CF_NAK_MAX_SEGMENTS, CF_NAK_MAX_SEGMENTS];

pub const CF_CHANNEL_NUM_TX_CHUNKS_PER_TRANSACTION: [u32; 2] = [CF_NAK_MAX_SEGMENTS, CF_NAK_MAX_SEGMENTS];

pub const CF_TOTAL_CHUNKS: u32 = CF_NAK_MAX_SEGMENTS * 4;

pub const CF_MISSION_REV: u32 = 0;